function voxels2image = find_projection_point(voxels, data)

[H, W, ~] = size(data(1).Image);
X = voxels.XData;
Y = voxels.YData;
Z = voxels.ZData;

for i = 1:numel(data)
    im_z = data(i).P(3,1) * X(:) + ...
        data(i).P(3,2) * Y(:) + ...
        data(i).P(3,3) * Z(:) + ...
        data(i).P(3,4);
    im_y = round(( data(i).P(2,1) * X(:) + ...
        data(i).P(2,2) * Y(:) + ...
        data(i).P(2,3) * Z(:) + ...
        data(i).P(2,4)) ./ im_z);
    im_x = round(( data(i).P(1,1) * X(:) + ...
        data(i).P(1,2) * Y(:) + ...
        data(i).P(1,3) * Z(:) + ...
        data(i).P(1,4)) ./ im_z);
    out_im = find( (im_x<1) | (im_x>W) | (im_y<1) | (im_y>H) );
    im_x(out_im) = 1;
    im_y(out_im) = 1;
    voxels2image(i).cord = [im_y, im_x];
end
end